### PR TITLE
add in a way to auto close the log

### PR DESCRIPTION
**Pull request by BanditTech**
this adds a click event listener which will close the window if it is already opened.

### CODE REVIEW

**Comment by anikethsaha** [comment]
I will release it soon

**Comment by BanditTech** [comment]
I have also done some major refactor of some parts of your CSS sheet.

https://bandittech.github.io/WingmanReloaded/#/

I have found a way to remove the ability to click on the links that are automatically generated by docsify. I made a ton of other changes to the CSS if you want to take a peek.

[here is the gh-pages branch](https://github.com/BanditTech/WingmanReloaded/tree/gh-pages)

**Comment by anikethsaha** [comment]
> I have found a way to remove the ability to click on the links that are automatically generated by docsify

actually I didnt come across this issue. But if you think its genuine then submit a PR we can discuss there

**Comment by BanditTech** [comment]
try creating a changlog.md which contains H1-4 and does not have any further marking. 

# H1
## H2
etc..

and you will see that the styling of the heading is that of a link, and the text will change color whether you have "clicked" on the heading or not.

**Comment by anikethsaha** [comment]
I have noticed one issue that whenever clicking on the changelog button moves the site to `/` url.
thats why I am not able to see the sidebar when its rendering. Can you check that if these are related. 

Anyway,  PR is welcome for both

**Pull request merged**
